<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.4.1" data-toc-modified-id="2.4.1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.4.1</a></span></li><li><span><a href="#1.20.3" data-toc-modified-id="1.20.3-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>1.20.3</a></span></li><li><span><a href="#1.3.4" data-toc-modified-id="1.3.4-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1.3.4</a></span></li><li><span><a href="#AFTER-UPDATE-TENSORFLOW" data-toc-modified-id="AFTER-UPDATE-TENSORFLOW-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>AFTER UPDATE TENSORFLOW</a></span></li><li><span><a href="#conda-upgrade-tensorflow" data-toc-modified-id="conda-upgrade-tensorflow-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>conda upgrade tensorflow</a></span></li></ul></div>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)
print(np.__version__)
print(pd.__version__)



2.4.1
1.20.3
1.3.4


# 2.4.1
# 1.20.3
# 1.3.4

# AFTER UPDATE TENSORFLOW
# conda upgrade tensorflow

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)
print(np.__version__)
print(pd.__version__)

2.5.0
1.19.5
1.3.4


In [3]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [5]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# AFTER 2.7 UPGRADE
python -m pip  install tensorflow==2.7

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf
print(tf.__version__)
print(np.__version__)
print(pd.__version__)


2.7.0
1.19.5
1.3.4


In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
a = tf.Variable(7)

In [6]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [8]:
a.numpy()

7

In [13]:
a = tf.Variable([0,1,2,3,4,5])
a,a.numpy()

(<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>,
 array([0, 1, 2, 3, 4, 5], dtype=int32))

In [18]:
a[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [37]:
a[-4:].numpy()

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]], dtype=int32)

In [24]:
a = tf.Variable([[0,1,2,3,4,5],[10,11,12,13,14,15]])

In [36]:
a.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'

In [40]:
vector = tf.Variable([10, 10])
vector


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [41]:
vector.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'