<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.4.1" data-toc-modified-id="2.4.1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.4.1</a></span></li><li><span><a href="#1.20.3" data-toc-modified-id="1.20.3-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>1.20.3</a></span></li><li><span><a href="#1.3.4" data-toc-modified-id="1.3.4-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1.3.4</a></span></li><li><span><a href="#AFTER-UPDATE-TENSORFLOW" data-toc-modified-id="AFTER-UPDATE-TENSORFLOW-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>AFTER UPDATE TENSORFLOW</a></span></li><li><span><a href="#conda-upgrade-tensorflow" data-toc-modified-id="conda-upgrade-tensorflow-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>conda upgrade tensorflow</a></span></li></ul></div>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)
print(np.__version__)
print(pd.__version__)



2.4.1
1.20.3
1.3.4


# 2.4.1
# 1.20.3
# 1.3.4

# AFTER UPDATE TENSORFLOW
# conda upgrade tensorflow

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)
print(np.__version__)
print(pd.__version__)

2.5.0
1.19.5
1.3.4


In [3]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [5]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# AFTER 2.7 UPGRADE
python -m pip  install tensorflow==2.7

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf
print(tf.__version__)
print(np.__version__)
print(pd.__version__)


2.7.0
1.19.5
1.3.4


In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
a = tf.Variable(7)

In [6]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [8]:
a.numpy()

7

In [13]:
a = tf.Variable([0,1,2,3,4,5])
a,a.numpy()

(<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>,
 array([0, 1, 2, 3, 4, 5], dtype=int32))

In [18]:
a[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [37]:
a[-4:].numpy()

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]], dtype=int32)

In [24]:
a = tf.Variable([[0,1,2,3,4,5],[10,11,12,13,14,15]])

In [36]:
a.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'

In [40]:
vector = tf.Variable([10, 10])
vector


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [41]:
vector.ndim

AttributeError: 'ResourceVariable' object has no attribute 'ndim'

In [61]:
a, b, c = {"a":12,"b":13,"c":14}

In [62]:
a[0]

'a'

In [63]:
b

'b'

In [64]:
pip install -q seaborn

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Note: you may need to restart the kernel to use updated packages.


In [65]:
!ls -l

total 56
-rw-r--r--   1 sree  staff  10787 Nov 22 22:15 00-SREE-TEST.ipynb
drwxr-xr-x  10 sree  staff    340 Nov 13 18:40 AI
drwxr-xr-x   7 sree  staff    238 Nov  7 17:59 Decision-Tree-Salries
drwxr-xr-x   3 sree  staff    102 Nov  7 23:36 HEATMAP
drwxr-xr-x   8 sree  staff    272 Nov  9 17:45 KNN-Classifier-Iris
drwxr-xr-x   7 sree  staff    238 Nov  7 17:53 Linear-Regression-Area-Bed-Age-Price
drwxr-xr-x   8 sree  staff    272 Nov 13 00:50 Linear-Regression-Area-Price
drwxr-xr-x   7 sree  staff    238 Nov  7 17:59 Logistic-Regression-Insurance
drwxr-xr-x   7 sree  staff    238 Nov  7 17:59 Logistic-Regression-Iris
drwxrwxr-x@ 27 sree  staff    918 Aug 31  2018 Refactored_Py_DS_ML_Bootcamp-master
drwxr-xr-x   9 sree  staff    306 Nov 21 23:38 TF-CERT
drwxr-xr-x  10 sree  staff    340 Nov  7 16:24 data
-rw-r--r--   1 sree  staff    887 Nov 14 11:01 docker-compose.yml
drwxr-xr-x   5 sree  staff    170 Nov 23 23:06 docs
drwxr-xr-x   3 sree  staff    102 Nov 24 19:36 kaggle
drwxr-xr-x  3

In [66]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [67]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

In [68]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [69]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)


In [70]:
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 3s 3s/step - loss: 54.1673
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 42.6165
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 33.5288
Epoch 4/500
1/1 [==============================] - 0s 9ms/step - loss: 26.3791
Epoch 5/500
1/1 [==============================] - 0s 6ms/step - loss: 20.7541
Epoch 6/500
1/1 [==============================] - 0s 12ms/step - loss: 16.3286
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 12.8468
Epoch 8/500
1/1 [==============================] - 0s 18ms/step - loss: 10.1075
Epoch 9/500
1/1 [==============================] - 0s 26ms/step - loss: 7.9523
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 6.2567
Epoch 11/500
1/1 [==============================] - 0s 13ms/step - loss: 4.9227
Epoch 12/500
1/1 [==============================] - 0s 10ms/step - loss: 3.8732
Epoch 13/500
1/1 [==============================]

1/1 [==============================] - 0s 10ms/step - loss: 1.7572e-04
Epoch 102/500
1/1 [==============================] - 0s 8ms/step - loss: 1.7211e-04
Epoch 103/500
1/1 [==============================] - 0s 6ms/step - loss: 1.6858e-04
Epoch 104/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6511e-04
Epoch 105/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6172e-04
Epoch 106/500
1/1 [==============================] - 0s 13ms/step - loss: 1.5840e-04
Epoch 107/500
1/1 [==============================] - 0s 6ms/step - loss: 1.5515e-04
Epoch 108/500
1/1 [==============================] - 0s 6ms/step - loss: 1.5196e-04
Epoch 109/500
1/1 [==============================] - 0s 13ms/step - loss: 1.4884e-04
Epoch 110/500
1/1 [==============================] - 0s 8ms/step - loss: 1.4578e-04
Epoch 111/500
1/1 [==============================] - 0s 12ms/step - loss: 1.4279e-04
Epoch 112/500
1/1 [==============================] - 0s 17ms/step - loss: 1.3986e-04
E

Epoch 198/500
1/1 [==============================] - 0s 8ms/step - loss: 2.3468e-05
Epoch 199/500
1/1 [==============================] - 0s 11ms/step - loss: 2.2986e-05
Epoch 200/500
1/1 [==============================] - 0s 10ms/step - loss: 2.2514e-05
Epoch 201/500
1/1 [==============================] - 0s 10ms/step - loss: 2.2051e-05
Epoch 202/500
1/1 [==============================] - 0s 13ms/step - loss: 2.1598e-05
Epoch 203/500
1/1 [==============================] - 0s 4ms/step - loss: 2.1154e-05
Epoch 204/500
1/1 [==============================] - 0s 15ms/step - loss: 2.0720e-05
Epoch 205/500
1/1 [==============================] - 0s 8ms/step - loss: 2.0294e-05
Epoch 206/500
1/1 [==============================] - 0s 25ms/step - loss: 1.9877e-05
Epoch 207/500
1/1 [==============================] - 0s 25ms/step - loss: 1.9468e-05
Epoch 208/500
1/1 [==============================] - 0s 53ms/step - loss: 1.9069e-05
Epoch 209/500
1/1 [==============================] - 0s 17ms/step - 

1/1 [==============================] - 0s 12ms/step - loss: 3.1999e-06
Epoch 295/500
1/1 [==============================] - 0s 11ms/step - loss: 3.1341e-06
Epoch 296/500
1/1 [==============================] - 0s 23ms/step - loss: 3.0698e-06
Epoch 297/500
1/1 [==============================] - 0s 14ms/step - loss: 3.0067e-06
Epoch 298/500
1/1 [==============================] - 0s 8ms/step - loss: 2.9451e-06
Epoch 299/500
1/1 [==============================] - 0s 12ms/step - loss: 2.8844e-06
Epoch 300/500
1/1 [==============================] - 0s 14ms/step - loss: 2.8253e-06
Epoch 301/500
1/1 [==============================] - ETA: 0s - loss: 2.7671e-0 - 0s 9ms/step - loss: 2.7671e-06
Epoch 302/500
1/1 [==============================] - 0s 17ms/step - loss: 2.7103e-06
Epoch 303/500
1/1 [==============================] - 0s 17ms/step - loss: 2.6544e-06
Epoch 304/500
1/1 [==============================] - 0s 7ms/step - loss: 2.6000e-06
Epoch 305/500
1/1 [==============================] - 0

1/1 [==============================] - 0s 6ms/step - loss: 4.3633e-07
Epoch 391/500
1/1 [==============================] - 0s 14ms/step - loss: 4.2739e-07
Epoch 392/500
1/1 [==============================] - 0s 12ms/step - loss: 4.1870e-07
Epoch 393/500
1/1 [==============================] - 0s 10ms/step - loss: 4.1007e-07
Epoch 394/500
1/1 [==============================] - 0s 10ms/step - loss: 4.0168e-07
Epoch 395/500
1/1 [==============================] - 0s 6ms/step - loss: 3.9342e-07
Epoch 396/500
1/1 [==============================] - 0s 10ms/step - loss: 3.8531e-07
Epoch 397/500
1/1 [==============================] - 0s 7ms/step - loss: 3.7742e-07
Epoch 398/500
1/1 [==============================] - 0s 10ms/step - loss: 3.6965e-07
Epoch 399/500
1/1 [==============================] - 0s 10ms/step - loss: 3.6211e-07
Epoch 400/500
1/1 [==============================] - 0s 5ms/step - loss: 3.5473e-07
Epoch 401/500
1/1 [==============================] - 0s 8ms/step - loss: 3.4743e-07

1/1 [==============================] - 0s 7ms/step - loss: 5.8394e-08
Epoch 488/500
1/1 [==============================] - 0s 7ms/step - loss: 5.7215e-08
Epoch 489/500
1/1 [==============================] - 0s 5ms/step - loss: 5.6015e-08
Epoch 490/500
1/1 [==============================] - 0s 6ms/step - loss: 5.4916e-08
Epoch 491/500
1/1 [==============================] - 0s 7ms/step - loss: 5.3754e-08
Epoch 492/500
1/1 [==============================] - 0s 5ms/step - loss: 5.2658e-08
Epoch 493/500
1/1 [==============================] - 0s 3ms/step - loss: 5.1616e-08
Epoch 494/500
1/1 [==============================] - 0s 5ms/step - loss: 5.0501e-08
Epoch 495/500
1/1 [==============================] - 0s 5ms/step - loss: 4.9514e-08
Epoch 496/500
1/1 [==============================] - 0s 5ms/step - loss: 4.8491e-08
Epoch 497/500
1/1 [==============================] - 0s 7ms/step - loss: 4.7468e-08
Epoch 498/500
1/1 [==============================] - 0s 6ms/step - loss: 4.6514e-08
Epoch 

In [71]:
print(model.predict([10.0]))

[[31.00062]]


In [72]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [73]:
model.

AttributeError: 'Sequential' object has no attribute 'coefficients'